export const colors = {
  // Primary purple (Building/Golden Hours)
  purple: {
    50: '#F5F3FF',
    100: '#EDE9FE',
    200: '#DDD6FE',
    300: '#C4B5FD',
    400: '#A78BFA',
    500: '#8B5CF6',
    600: '#7C3AED',
    700: '#6D28D9',
    800: '#5B21B6',
    900: '#4C1D95',
    ring: '#EFABFE',
    progress: '#A855F7',
  },
  // Gold/Orange (Marketing)
  gold: {
    50: '#FFFBEB',
    100: '#FEF3C7',
    200: '#FDE68A',
    300: '#FCD34D',
    400: '#FBBF24',
    500: '#F59E0B',
    600: '#D97706',
    700: '#B45309',
    800: '#92400E',
    900: '#78350F',
    ring: '#E9C08F',
    progress: '#FB923C',
  },
  // Yellow/Cream (Learning)
  cream: {
    50: '#FEFCE8',
    100: '#FEF9C3',
    200: '#FEF08A',
    300: '#FDE047',
    400: '#FACC15',
    500: '#EAB308',
    ring: '#EFE1B7',
    progress: '#FDE047',
  },
  // Slate for neutrals
  slate: {
    50: '#F8FAFC',
    100: '#F1F5F9',
    200: '#E2E8F0',
    300: '#CBD5E1',
    400: '#94A3B8',
    500: '#64748B',
    600: '#475569',
    700: '#334155',
    800: '#1E293B',
    900: '#0F172A',
  },
  // Mood scale colors (1-10)
  mood: {
    1: '#EF4444',
    2: '#F97316',
    3: '#FB923C',
    4: '#FBBF24',
    5: '#FACC15',
    6: '#A3E635',
    7: '#4ADE80',
    8: '#22C55E',
    9: '#10B981',
    10: '#34D399',
  },
  // Semantic
  background: '#FFFFFF',
  card: '#FFFFFF',
  text: {
    primary: '#1F2937',
    secondary: '#6B7280',
    muted: '#9CA3AF',
  },
  border: '#E5E7EB',
  success: '#22C55E',
  warning: '#EAB308',
  error: '#EF4444',
} as const;

// Metric definitions with updated design colors
export const METRICS = {
  building: {
    key: 'buildingMinutes',
    label: 'Building',
    description: 'Creating products, writing code, designing, shipping.',
    type: 'time' as const,
    category: 'positive' as const,
    increment: 15,
    color: colors.purple[500],
    ringBg: colors.purple.ring,
    ringProgress: colors.purple.progress,
  },
  marketing: {
    key: 'marketingMinutes',
    label: 'Marketing',
    description: 'Distribution, writing, posting, outreach, audience growth.',
    type: 'time' as const,
    category: 'positive' as const,
    increment: 15,
    color: colors.gold[500],
    ringBg: colors.gold.ring,
    ringProgress: colors.gold.progress,
  },
  levelingUp: {
    key: 'levelingUpMinutes',
    label: 'Learn',
    description: 'Learning, reading, courses, tutorials, skill improvement.',
    type: 'time' as const,
    category: 'positive' as const,
    increment: 15,
    color: colors.cream[400],
    ringBg: colors.cream.ring,
    ringProgress: colors.cream.progress,
  },
  workout: {
    key: 'workoutMinutes',
    label: 'Exercise',
    description: 'Any intentional physical exercise.\n20 min a day is 140 mins a week.',
    type: 'time' as const,
    category: 'positive' as const,
    increment: 5,
    color: colors.purple[400],
    ringBg: colors.purple[100],
    ringProgress: colors.purple[500],
  },
  drinks: {
    key: 'drinks',
    label: 'Drinks',
    description: 'Number of alcoholic drinks consumed.',
    type: 'count' as const,
    category: 'negative' as const,
    increment: 1,
    color: colors.gold[400],
    ringBg: colors.gold[100],
    ringProgress: colors.gold[500],
  },
  streaming: {
    key: 'tvMinutes',
    label: 'Streaming',
    description: 'Passive screen consumption not related to learning or building.',
    type: 'time' as const,
    category: 'negative' as const,
    increment: 15,
    color: colors.gold[300],
    ringBg: colors.gold[100],
    ringProgress: colors.gold[400],
  },
} as const;

export type MetricKey = keyof typeof METRICS;
